optimize warp to use different hosts for each conn
minio/warp pull request #136
Opened 2020-09-21 20:22 UTC by harshavardhana

this is useful when `warp` is going through a RR-DNS
or a DNS which resolves to multiple other hosts

so a `--host` is a DNS and resolves to multiple hosts
warp will automatically/randomly use a different host
for each new connection

2020-09-22 09:04 UTC, klauspost requested changes
I fail to see how this is much different from the current approach since connections are reused.

The default dialer will try the addresses in order whereas this will pick a random. However once a client has a connection it will keep reusing it.

If a RR-DNS returns the same order of clients it isn't really that doing its job since it should be returning entries in a different order for each. Once a connection is open it will not change unless the server closes the connection.

So I am not sure what case this is fixing.

2020-09-22 09:04 UTC, klauspost commented on cli/client.go
> +var rng = rand.New(rand.NewSource(time.Now().UTC().UnixNano()))
`rand.NewSource` is not safe for concurrent use.

Should be placed in `newCustomDialContext`, along with a lock.

2020-09-22 09:04 UTC, klauspost commented on cli/client.go
> +		}
It is safe to concurrently use a Dialer.
```suggestion
		dialer := &net.Dialer{
			Timeout:   dialTimeout,
			KeepAlive: dialKeepAlive,
		}

		return func(ctx context.Context, network, addr string) (net.Conn, error) {
```

2020-10-07 20:01 UTC, harshavardhana commented
Closing this as this is not useful

2020-10-07 20:01 UTC, closed without merging