add --trace-http hidden flag to set TraceOn to minio client
minio/warp pull request #252
Opened 2023-03-01 04:33 UTC by fatpat

2023-03-01 08:38 UTC, klauspost approved these changes
LGTM

2023-03-02 14:16 UTC, klauspost requested changes
Sorry for changing my mind. Could we make it `--debug` - that way it matches our other tools.

2023-03-02 14:16 UTC, klauspost commented on cli/client.go
> +	if ctx.Bool("trace-http") {
```suggestion
	if ctx.Bool("debug") {
```

2023-03-02 14:16 UTC, klauspost commented on cli/flags.go
> +		Name:   "trace-http",
```suggestion
		Name:   "debug",
```

2023-03-02 19:58 UTC, fatpat commented on cli/flags.go
> +		Name:   "trace-http",
there is already a `--debug` flag. Either we use it and set `TraceOn` when `--debug` is set or use another one like `--debug-http`.

what do you prefer ?

2023-03-02 23:35 UTC, harshavardhana commented on cli/flags.go
> +		Name:   "trace-http",
The same debug flag can be used @fatpat

2023-03-03 05:27 UTC, fatpat commented on cli/flags.go
> +		Name:   "trace-http",
fixed

2023-03-03 07:16 UTC, klauspost approved these changes

2023-03-03 07:41 UTC, merged